"""
Django settings for log_monitor project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

if os.environ.get('DJANGO_PRODUCTION_SETTINGS',None):
    from .pro_settings import *
else:
    from .dev_settings import *