# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlibblifeWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlilifeServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BizServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=225)),
                ('desc', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='LogMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('USER', 'USERLOG'), ('PAY', 'PAYLOG'), ('BIZ', 'BIZLOG'), ('ADMIN', 'ADMINLOG'), ('ALIBBLIFE', 'ALIBBLIFELOG'), ('COMM', 'COMMLOG'), ('CONFIG', 'CONFIGLOG'), ('MOBILE', 'MOBILELOG'), ('ORDER', 'OADERLOG'), ('PROMOTION', 'PROMOTIONLOG'), ('SHOP', 'SHOPLOG'), ('WAP', 'WAPLOG'), ('WX', 'WXLOG')], max_length=100)),
                ('log_path', models.CharField(max_length=500)),
                ('timing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PayServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SshConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=225)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WapWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WxServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
    ]
