# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('TP1', 'USERLOG'), ('TP2', 'PAYLOG')], max_length=10)),
                ('log_level', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='logmonitor',
            name='log_type',
            field=models.CharField(choices=[('TP1', 'USERLOG'), ('TP2', 'PAYLOG')], max_length=10),
        ),
    ]
