# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0003_auto_20171016_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='log_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='log_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyze.LogMonitor'),
        ),
        migrations.AlterField(
            model_name='logmonitor',
            name='log_type',
            field=models.CharField(choices=[('USER', 'USERLOG'), ('PAY', 'PAYLOG')], max_length=100),
        ),
    ]
