# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0005_auto_20171017_0604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogData',
            new_name='UserLog',
        ),
    ]
