# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0009_loglevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizLogError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
    ]
