# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0010_bizlogerror'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BizLogError',
            new_name='BizServiceError',
        ),
    ]
