# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0011_auto_20171101_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmonitor',
            name='log_type',
            field=models.CharField(choices=[('USER', 'USERLOG'), ('PAY', 'PAYLOG'), ('BIZ', 'BIZLOG')], max_length=100),
        ),
    ]
