# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0012_auto_20171101_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmonitor',
            name='log_path',
            field=models.CharField(max_length=500),
        ),
    ]
