# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0013_auto_20171101_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlibblifeWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlilifeServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PayServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PromotionServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WapWebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WxServiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=225)),
                ('log_level', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
    ]
