# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0014_adminweberror_alibblifeweberror_alilifeserviceerror_communicationserviceerror_configserviceerror_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmonitor',
            name='log_type',
            field=models.CharField(choices=[('USER', 'USERLOG'), ('PAY', 'PAYLOG'), ('BIZ', 'BIZLOG'), ('ADMIN', 'ADMINLOG'), ('ALIBBLIFE', 'ALIBBLIFELOG'), ('COMM', 'COMMLOG'), ('CONFIG', 'CONFIGLOG'), ('MOBILE', 'MOBILELOG'), ('ORDER', 'OADERLOG'), ('PROMOTION', 'PROMOTIONLOG'), ('SHOP', 'SHOPLOG'), ('WAP', 'WAPLOG'), ('WX', 'WXLOG')], max_length=100),
        ),
    ]
