# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyze', '0015_auto_20171101_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=225)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
